version: '3.8'

services:

  api:
    image: node:fermium-alpine
    command: yarn start:dev
    depends_on: 
      - redis
      - mongodb
    ports: 
      - "3000:3000"
      - "9229:9229"
    volumes: 
      - ./:/app
    working_dir: /app
    networks: 
      - "rs_ws_env_nw"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

networks: 
  rs_ws_env_nw: